[package]
name = "petabyte-scale-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
http = { workspace = true }

[lib]
name = "petabyte_scale_engine"
path = "src/lib.rs"

[[bin]]
name = "petabyte_scale_engine_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


