[package]
name = "service-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true }
thiserror = { workspace = true }
blake3 = "1"
log = "0.4"
env_logger = { workspace = true }

[lib]
name = "service_manager"
path = "src/lib.rs"

[[bin]]
name = "service_manager_debug"
path = "src/bin/debug.rs"

[dev-dependencies]
