//! Bonsai Extension → MCP Server exporter.
//!
//! Generates a standalone Model Context Protocol server (JSON-RPC over stdio)
//! that exposes the extension's tools. This is the highest-ROI export target:
//! any Claude / Continue / Cursor user gets the extension with zero IDE coupling.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde_json::json;
use tracing::info;

use crate::ir::{Capability, ExtensionIr};
use crate::ConversionError;

/// Output of MCP export: a directory containing the server files.
pub struct McpExportResult {
    pub output_dir: PathBuf,
    pub entry_point: String,
    pub tool_count: usize,
    pub readme: String,
}

/// Export a Bonsai extension as a standalone MCP server (Rust source + Cargo.toml).
pub async fn export_as_mcp(
    ir: &ExtensionIr,
    output_dir: &Path,
) -> Result<McpExportResult, ConversionError> {
    tokio::fs::create_dir_all(output_dir)
        .await
        .map_err(|e| ConversionError::Io(e.to_string()))?;

    let tools: Vec<_> = ir.capabilities.iter().filter_map(|cap| {
        if let Capability::Tool(t) = cap { Some(t) } else { None }
    }).collect();

    // Also expose commands as tools
    let command_tools: Vec<_> = ir.capabilities.iter().filter_map(|cap| {
        if let Capability::Command(c) = cap { Some(c) } else { None }
    }).collect();

    let tool_count = tools.len() + command_tools.len();

    info!(ext = %ir.metadata.id, tools = tool_count, "[mcp-export] generating MCP server");

    // Generate server_tools.json — the MCP tool manifest
    let mut mcp_tools: Vec<serde_json::Value> = Vec::new();

    for t in &tools {
        mcp_tools.push(json!({
            "name": t.id,
            "description": t.description,
            "inputSchema": t.input_schema,
        }));
    }
    for c in &command_tools {
        mcp_tools.push(json!({
            "name": c.id.replace('.', "_"),
            "description": format!("{} (from VSCode command {})", c.title, c.id),
            "inputSchema": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }));
    }

    let tools_json = serde_json::to_string_pretty(&json!({
        "tools": mcp_tools
    })).map_err(|e| ConversionError::Io(e.to_string()))?;

    tokio::fs::write(output_dir.join("mcp_tools.json"), &tools_json)
        .await
        .map_err(|e| ConversionError::Io(e.to_string()))?;

    // Generate Cargo.toml for the MCP server binary
    let cargo_toml = format!(
        r#"[package]
name = "{name}-mcp"
version = "{version}"
edition = "2021"
description = "MCP server for {display_name}"

[[bin]]
name = "{name}-mcp"
path = "src/main.rs"

[dependencies]
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tokio = {{ version = "1", features = ["full"] }}
"#,
        name = ir.metadata.id.replace('.', "-"),
        version = ir.metadata.version,
        display_name = ir.metadata.name,
    );

    tokio::fs::create_dir_all(output_dir.join("src"))
        .await
        .map_err(|e| ConversionError::Io(e.to_string()))?;
    tokio::fs::write(output_dir.join("Cargo.toml"), &cargo_toml)
        .await
        .map_err(|e| ConversionError::Io(e.to_string()))?;

    // Generate src/main.rs — a minimal MCP server over stdio
    let tool_match_arms = mcp_tools.iter().map(|t| {
        let name = t["name"].as_str().unwrap_or("unknown");
        format!(
            r#"            "{name}" => {{
                // TODO: wire to actual extension logic
                serde_json::json!({{"content": [{{"type": "text", "text": "Tool {name} called"}}]}})
            }}"#,
            name = name
        )
    }).collect::<Vec<_>>().join("\n");

    let tools_array_literal = mcp_tools.iter().map(|t| {
        serde_json::to_string(t).unwrap_or_default()
    }).collect::<Vec<_>>().join(",\n        ");

    let main_rs = format!(
        r#"//! Auto-generated MCP server for {display_name}.
//! Generated by bonsai-extension-converter.

use std::io::{{BufRead, Write}};
use serde_json::{{json, Value}};

fn main() {{
    let stdin = std::io::stdin();
    let stdout = std::io::stdout();
    let mut out = stdout.lock();

    for line in stdin.lock().lines() {{
        let line = match line {{ Ok(l) => l, Err(_) => break }};
        if line.is_empty() {{ continue; }}

        let request: Value = match serde_json::from_str(&line) {{
            Ok(v) => v,
            Err(_) => continue,
        }};

        let id = request.get("id").cloned().unwrap_or(Value::Null);
        let method = request["method"].as_str().unwrap_or("");

        let result = match method {{
            "initialize" => json!({{
                "protocolVersion": "2024-11-05",
                "capabilities": {{"tools": {{}}}},
                "serverInfo": {{"name": "{name}", "version": "{version}"}}
            }}),
            "tools/list" => json!({{
                "tools": [
        {tools_array}
                ]
            }}),
            "tools/call" => {{
                let tool_name = request["params"]["name"].as_str().unwrap_or("");
                match tool_name {{
{match_arms}
                    _ => json!({{"content": [{{"type": "text", "text": format!("Unknown tool: {{}}", tool_name)}}], "isError": true}})
                }}
            }},
            _ => json!({{"error": {{"code": -32601, "message": "Method not found"}}}}),
        }};

        let response = json!({{"jsonrpc": "2.0", "id": id, "result": result}});
        let _ = writeln!(out, "{{}}", serde_json::to_string(&response).unwrap_or_default());
        let _ = out.flush();
    }}
}}
"#,
        display_name = ir.metadata.name,
        name = ir.metadata.id.replace('.', "-"),
        version = ir.metadata.version,
        tools_array = tools_array_literal,
        match_arms = tool_match_arms,
    );

    tokio::fs::write(output_dir.join("src/main.rs"), &main_rs)
        .await
        .map_err(|e| ConversionError::Io(e.to_string()))?;

    let readme = format!(
        "# {name} — MCP Server\n\nGenerated by Bonsai Extension Converter.\n\n## Install\n```\ncargo build --release\n```\n\n## Claude Desktop Config\n```json\n{{\n  \"mcpServers\": {{\n    \"{id}\": {{\n      \"command\": \"./target/release/{id}-mcp\"\n    }}\n  }}\n}}\n```\n\n## Tools ({count})\n{tools}\n",
        name = ir.metadata.name,
        id = ir.metadata.id.replace('.', "-"),
        count = tool_count,
        tools = mcp_tools.iter().map(|t| format!("- `{}`", t["name"].as_str().unwrap_or(""))).collect::<Vec<_>>().join("\n"),
    );

    tokio::fs::write(output_dir.join("README.md"), &readme)
        .await
        .map_err(|e| ConversionError::Io(e.to_string()))?;

    info!(ext = %ir.metadata.id, "[mcp-export] MCP server generated");

    Ok(McpExportResult {
        output_dir: output_dir.to_path_buf(),
        entry_point: "src/main.rs".into(),
        tool_count,
        readme,
    })
}
