[package]
name = "data-table-component"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lib]
name = "data_table_component"
path = "src/lib.rs"

[[bin]]
name = "data_table_component_cli"
path = "src/bin/cli.rs"



