[package]
name = "transfer-ai"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }

[lib]
name = "transfer_ai"
path = "src/lib.rs"

[[bin]]
name = "transfer_ai_cli"
path = "src/bin/cli.rs"

[dev-dependencies]

