[package]
name = "freellmapi-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
freellmapi-core = { path = "../freellmapi-core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
sqlx = { version = "0.9", features = ["sqlite", "runtime-tokio"] }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
name = "freellmapi_storage"
path = "src/lib.rs"

[[bin]]
name = "freellmapi_storage_cli"
path = "src/bin/cli.rs"

