[package]
name = "traffic-management"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
rand = "0.8"

[lib]
name = "traffic_management"
path = "src/lib.rs"

[[bin]]
name = "traffic_management_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


