[package]
name = "backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
sysinfo = "0.30"
ndarray = "0.15"
log = "0.4"

[features]
cuda = []
rocm = []
directml = []

[lib]
name = "backend"
path = "src/lib.rs"

[[bin]]
name = "backend_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
env_logger = { workspace = true }
anyhow = { workspace = true }

