[package]
name = "advanced-monitoring"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }

[lib]
name = "advanced_monitoring"
path = "src/lib.rs"

[[bin]]
name = "advanced_monitoring_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
tokio = { workspace = true }

