[package]
name = "bmn-encoder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
bmn-common = { path = "../bmn-common" }

[lib]
name = "bmn_encoder"
path = "src/lib.rs"

[[bin]]
name = "bmn_encoder_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


