[package]
name = "bedf-fuzzing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rand = "0.8"
serde = { workspace = true }
anyhow = { workspace = true }

[lib]
name = "bedf_fuzzing"
path = "src/lib.rs"

[[bin]]
name = "bedf_fuzzing_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
tokio = { workspace = true }
