[package]
name = "sylva"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "sylva"
path = "src/lib.rs"

[[bin]]
name = "sylva_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


