[package]
name = "titan-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
im = "15"
parking_lot = { workspace = true }

[lib]
name = "titan_core"
path = "src/lib.rs"

[[bin]]
name = "titan_core_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


