[package]
name = "event-sourcing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[lib]
name = "event_sourcing"
path = "src/lib.rs"

[[bin]]
name = "event_sourcing_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


