[package]
name = "pre-launcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
num_cpus = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }

[lib]
name = "pre_launcher"
path = "src/lib.rs"

[[bin]]
name = "pre_launcher_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


