[package]
name = "request-hedging"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }

[lib]
name = "request_hedging"
path = "src/lib.rs"

[[bin]]
name = "request_hedging_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


