[package]
name = "performance-tuning-advisor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[lib]
name = "performance_tuning_advisor"
path = "src/lib.rs"

[[bin]]
name = "performance_tuning_advisor_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


