[package]
name = "service-coordination"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lib]
name = "service_coordination"
path = "src/lib.rs"

[[bin]]
name = "service_coordination_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


