[package]
name = "bat"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
ndarray = "0.15"
rand = "0.8"

[lib]
name = "bat"
path = "src/lib.rs"

[[bin]]
name = "bat_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


