[package]
name = "omnibot"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }

[lib]
name = "omnibot"
path = "src/lib.rs"

[[bin]]
name = "omnibot_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


