[package]
name = "bedf-sanitizers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }

[lib]
name = "bedf_sanitizers"
path = "src/lib.rs"

[[bin]]
name = "bedf_sanitizers_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


