[package]
name = "eternal-workshop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
log = "0.4"
env_logger = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
dirs = "5"
sqlx = { version = "0.9", features = ["sqlite", "runtime-tokio"] }
tempfile = { workspace = true }

[lib]
name = "eternal_workshop"
path = "src/lib.rs"

[[bin]]
name = "eternal_workshop_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
