[package]
name = "data-privacy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lib]
name = "data_privacy"
path = "src/lib.rs"

[[bin]]
name = "data_privacy_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


