# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import omniharness_pb2 as omniharness__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in omniharness_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventStoreServiceStub:
    """═══════════════════════════════════════════════════════════════════════════
    OmniHarness Century Protocol v1
    Polyglot AI Harness — Rust Kernel / Python Orchestrator / Clojure Planner
    ═══════════════════════════════════════════════════════════════════════════

    ─── 1. EVENT STORE ─────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEvent = channel.unary_unary(
                '/omniharness.v1.EventStoreService/AppendEvent',
                request_serializer=omniharness__pb2.AppendRequest.SerializeToString,
                response_deserializer=omniharness__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.VerifyChain = channel.unary_unary(
                '/omniharness.v1.EventStoreService/VerifyChain',
                request_serializer=omniharness__pb2.VerifyRequest.SerializeToString,
                response_deserializer=omniharness__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.QueryEvents = channel.unary_stream(
                '/omniharness.v1.EventStoreService/QueryEvents',
                request_serializer=omniharness__pb2.QueryRequest.SerializeToString,
                response_deserializer=omniharness__pb2.SystemEvent.FromString,
                _registered_method=True)
        self.GetTip = channel.unary_unary(
                '/omniharness.v1.EventStoreService/GetTip',
                request_serializer=omniharness__pb2.TipRequest.SerializeToString,
                response_deserializer=omniharness__pb2.TipResponse.FromString,
                _registered_method=True)


class EventStoreServiceServicer:
    """═══════════════════════════════════════════════════════════════════════════
    OmniHarness Century Protocol v1
    Polyglot AI Harness — Rust Kernel / Python Orchestrator / Clojure Planner
    ═══════════════════════════════════════════════════════════════════════════

    ─── 1. EVENT STORE ─────────────────────────────────────────────────────────

    """

    def AppendEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=omniharness__pb2.AppendRequest.FromString,
                    response_serializer=omniharness__pb2.AppendResponse.SerializeToString,
            ),
            'VerifyChain': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyChain,
                    request_deserializer=omniharness__pb2.VerifyRequest.FromString,
                    response_serializer=omniharness__pb2.VerifyResponse.SerializeToString,
            ),
            'QueryEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryEvents,
                    request_deserializer=omniharness__pb2.QueryRequest.FromString,
                    response_serializer=omniharness__pb2.SystemEvent.SerializeToString,
            ),
            'GetTip': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTip,
                    request_deserializer=omniharness__pb2.TipRequest.FromString,
                    response_serializer=omniharness__pb2.TipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.EventStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.EventStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventStoreService:
    """═══════════════════════════════════════════════════════════════════════════
    OmniHarness Century Protocol v1
    Polyglot AI Harness — Rust Kernel / Python Orchestrator / Clojure Planner
    ═══════════════════════════════════════════════════════════════════════════

    ─── 1. EVENT STORE ─────────────────────────────────────────────────────────

    """

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.EventStoreService/AppendEvent',
            omniharness__pb2.AppendRequest.SerializeToString,
            omniharness__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.EventStoreService/VerifyChain',
            omniharness__pb2.VerifyRequest.SerializeToString,
            omniharness__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/omniharness.v1.EventStoreService/QueryEvents',
            omniharness__pb2.QueryRequest.SerializeToString,
            omniharness__pb2.SystemEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.EventStoreService/GetTip',
            omniharness__pb2.TipRequest.SerializeToString,
            omniharness__pb2.TipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelServiceStub:
    """─── 2. MODEL SERVICE ────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/omniharness.v1.ModelService/Chat',
                request_serializer=omniharness__pb2.ChatRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/omniharness.v1.ModelService/ChatStream',
                request_serializer=omniharness__pb2.ChatRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/omniharness.v1.ModelService/ListModels',
                request_serializer=omniharness__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/omniharness.v1.ModelService/HealthCheck',
                request_serializer=omniharness__pb2.ModelHealthRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ModelHealthResponse.FromString,
                _registered_method=True)
        self.RegisterModel = channel.unary_unary(
                '/omniharness.v1.ModelService/RegisterModel',
                request_serializer=omniharness__pb2.RegisterModelReq.SerializeToString,
                response_deserializer=omniharness__pb2.RegisterModelResp.FromString,
                _registered_method=True)


class ModelServiceServicer:
    """─── 2. MODEL SERVICE ────────────────────────────────────────────────────────

    """

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=omniharness__pb2.ChatRequest.FromString,
                    response_serializer=omniharness__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=omniharness__pb2.ChatRequest.FromString,
                    response_serializer=omniharness__pb2.ChatChunk.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=omniharness__pb2.ListModelsRequest.FromString,
                    response_serializer=omniharness__pb2.ListModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=omniharness__pb2.ModelHealthRequest.FromString,
                    response_serializer=omniharness__pb2.ModelHealthResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=omniharness__pb2.RegisterModelReq.FromString,
                    response_serializer=omniharness__pb2.RegisterModelResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService:
    """─── 2. MODEL SERVICE ────────────────────────────────────────────────────────

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ModelService/Chat',
            omniharness__pb2.ChatRequest.SerializeToString,
            omniharness__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/omniharness.v1.ModelService/ChatStream',
            omniharness__pb2.ChatRequest.SerializeToString,
            omniharness__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ModelService/ListModels',
            omniharness__pb2.ListModelsRequest.SerializeToString,
            omniharness__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ModelService/HealthCheck',
            omniharness__pb2.ModelHealthRequest.SerializeToString,
            omniharness__pb2.ModelHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ModelService/RegisterModel',
            omniharness__pb2.RegisterModelReq.SerializeToString,
            omniharness__pb2.RegisterModelResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub:
    """─── 3. MEMORY SERVICE ───────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Store = channel.unary_unary(
                '/omniharness.v1.MemoryService/Store',
                request_serializer=omniharness__pb2.StoreRequest.SerializeToString,
                response_deserializer=omniharness__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/omniharness.v1.MemoryService/Retrieve',
                request_serializer=omniharness__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=omniharness__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.SearchSemantic = channel.unary_unary(
                '/omniharness.v1.MemoryService/SearchSemantic',
                request_serializer=omniharness__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=omniharness__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/omniharness.v1.MemoryService/Delete',
                request_serializer=omniharness__pb2.DeleteRequest.SerializeToString,
                response_deserializer=omniharness__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/omniharness.v1.MemoryService/ListCollections',
                request_serializer=omniharness__pb2.ListCollRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ListCollResponse.FromString,
                _registered_method=True)
        self.Summarize = channel.unary_unary(
                '/omniharness.v1.MemoryService/Summarize',
                request_serializer=omniharness__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=omniharness__pb2.SummarizeResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """─── 3. MEMORY SERVICE ───────────────────────────────────────────────────────

    """

    def Store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSemantic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Store': grpc.unary_unary_rpc_method_handler(
                    servicer.Store,
                    request_deserializer=omniharness__pb2.StoreRequest.FromString,
                    response_serializer=omniharness__pb2.StoreResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=omniharness__pb2.RetrieveRequest.FromString,
                    response_serializer=omniharness__pb2.RetrieveResponse.SerializeToString,
            ),
            'SearchSemantic': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSemantic,
                    request_deserializer=omniharness__pb2.SemanticSearchRequest.FromString,
                    response_serializer=omniharness__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=omniharness__pb2.DeleteRequest.FromString,
                    response_serializer=omniharness__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=omniharness__pb2.ListCollRequest.FromString,
                    response_serializer=omniharness__pb2.ListCollResponse.SerializeToString,
            ),
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=omniharness__pb2.SummarizeRequest.FromString,
                    response_serializer=omniharness__pb2.SummarizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """─── 3. MEMORY SERVICE ───────────────────────────────────────────────────────

    """

    @staticmethod
    def Store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MemoryService/Store',
            omniharness__pb2.StoreRequest.SerializeToString,
            omniharness__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MemoryService/Retrieve',
            omniharness__pb2.RetrieveRequest.SerializeToString,
            omniharness__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSemantic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MemoryService/SearchSemantic',
            omniharness__pb2.SemanticSearchRequest.SerializeToString,
            omniharness__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MemoryService/Delete',
            omniharness__pb2.DeleteRequest.SerializeToString,
            omniharness__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MemoryService/ListCollections',
            omniharness__pb2.ListCollRequest.SerializeToString,
            omniharness__pb2.ListCollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MemoryService/Summarize',
            omniharness__pb2.SummarizeRequest.SerializeToString,
            omniharness__pb2.SummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolServiceStub:
    """─── 4. TOOL SERVICE ─────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/omniharness.v1.ToolService/Execute',
                request_serializer=omniharness__pb2.ToolExecuteRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ToolExecuteResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/omniharness.v1.ToolService/Register',
                request_serializer=omniharness__pb2.ToolRegisterRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ToolRegisterResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/omniharness.v1.ToolService/List',
                request_serializer=omniharness__pb2.ToolListRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ToolListResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/omniharness.v1.ToolService/Unregister',
                request_serializer=omniharness__pb2.ToolUnregRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ToolUnregResponse.FromString,
                _registered_method=True)


class ToolServiceServicer:
    """─── 4. TOOL SERVICE ─────────────────────────────────────────────────────────

    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=omniharness__pb2.ToolExecuteRequest.FromString,
                    response_serializer=omniharness__pb2.ToolExecuteResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=omniharness__pb2.ToolRegisterRequest.FromString,
                    response_serializer=omniharness__pb2.ToolRegisterResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=omniharness__pb2.ToolListRequest.FromString,
                    response_serializer=omniharness__pb2.ToolListResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=omniharness__pb2.ToolUnregRequest.FromString,
                    response_serializer=omniharness__pb2.ToolUnregResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService:
    """─── 4. TOOL SERVICE ─────────────────────────────────────────────────────────

    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ToolService/Execute',
            omniharness__pb2.ToolExecuteRequest.SerializeToString,
            omniharness__pb2.ToolExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ToolService/Register',
            omniharness__pb2.ToolRegisterRequest.SerializeToString,
            omniharness__pb2.ToolRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ToolService/List',
            omniharness__pb2.ToolListRequest.SerializeToString,
            omniharness__pb2.ToolListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.ToolService/Unregister',
            omniharness__pb2.ToolUnregRequest.SerializeToString,
            omniharness__pb2.ToolUnregResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionServiceStub:
    """─── 5. SESSION SERVICE ──────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/omniharness.v1.SessionService/CreateSession',
                request_serializer=omniharness__pb2.CreateSessionReq.SerializeToString,
                response_deserializer=omniharness__pb2.CreateSessionResp.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/omniharness.v1.SessionService/GetSession',
                request_serializer=omniharness__pb2.GetSessionReq.SerializeToString,
                response_deserializer=omniharness__pb2.GetSessionResp.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/omniharness.v1.SessionService/ListSessions',
                request_serializer=omniharness__pb2.ListSessionsReq.SerializeToString,
                response_deserializer=omniharness__pb2.ListSessionsResp.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/omniharness.v1.SessionService/DeleteSession',
                request_serializer=omniharness__pb2.DeleteSessionReq.SerializeToString,
                response_deserializer=omniharness__pb2.DeleteSessionResp.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """─── 5. SESSION SERVICE ──────────────────────────────────────────────────────

    """

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=omniharness__pb2.CreateSessionReq.FromString,
                    response_serializer=omniharness__pb2.CreateSessionResp.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=omniharness__pb2.GetSessionReq.FromString,
                    response_serializer=omniharness__pb2.GetSessionResp.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=omniharness__pb2.ListSessionsReq.FromString,
                    response_serializer=omniharness__pb2.ListSessionsResp.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=omniharness__pb2.DeleteSessionReq.FromString,
                    response_serializer=omniharness__pb2.DeleteSessionResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """─── 5. SESSION SERVICE ──────────────────────────────────────────────────────

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.SessionService/CreateSession',
            omniharness__pb2.CreateSessionReq.SerializeToString,
            omniharness__pb2.CreateSessionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.SessionService/GetSession',
            omniharness__pb2.GetSessionReq.SerializeToString,
            omniharness__pb2.GetSessionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.SessionService/ListSessions',
            omniharness__pb2.ListSessionsReq.SerializeToString,
            omniharness__pb2.ListSessionsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.SessionService/DeleteSession',
            omniharness__pb2.DeleteSessionReq.SerializeToString,
            omniharness__pb2.DeleteSessionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HarnessServiceStub:
    """─── 6. HARNESS CONTROL ──────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/omniharness.v1.HarnessService/Status',
                request_serializer=omniharness__pb2.StatusRequest.SerializeToString,
                response_deserializer=omniharness__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Config = channel.unary_unary(
                '/omniharness.v1.HarnessService/Config',
                request_serializer=omniharness__pb2.ConfigRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/omniharness.v1.HarnessService/Reload',
                request_serializer=omniharness__pb2.ReloadRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.Metrics = channel.unary_unary(
                '/omniharness.v1.HarnessService/Metrics',
                request_serializer=omniharness__pb2.MetricsRequest.SerializeToString,
                response_deserializer=omniharness__pb2.MetricsResponse.FromString,
                _registered_method=True)


class HarnessServiceServicer:
    """─── 6. HARNESS CONTROL ──────────────────────────────────────────────────────

    """

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Metrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=omniharness__pb2.StatusRequest.FromString,
                    response_serializer=omniharness__pb2.StatusResponse.SerializeToString,
            ),
            'Config': grpc.unary_unary_rpc_method_handler(
                    servicer.Config,
                    request_deserializer=omniharness__pb2.ConfigRequest.FromString,
                    response_serializer=omniharness__pb2.ConfigResponse.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=omniharness__pb2.ReloadRequest.FromString,
                    response_serializer=omniharness__pb2.ReloadResponse.SerializeToString,
            ),
            'Metrics': grpc.unary_unary_rpc_method_handler(
                    servicer.Metrics,
                    request_deserializer=omniharness__pb2.MetricsRequest.FromString,
                    response_serializer=omniharness__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.HarnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.HarnessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HarnessService:
    """─── 6. HARNESS CONTROL ──────────────────────────────────────────────────────

    """

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.HarnessService/Status',
            omniharness__pb2.StatusRequest.SerializeToString,
            omniharness__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.HarnessService/Config',
            omniharness__pb2.ConfigRequest.SerializeToString,
            omniharness__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.HarnessService/Reload',
            omniharness__pb2.ReloadRequest.SerializeToString,
            omniharness__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Metrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.HarnessService/Metrics',
            omniharness__pb2.MetricsRequest.SerializeToString,
            omniharness__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MeshServiceStub:
    """─── 7. MESH / P2P ───────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastEvent = channel.unary_unary(
                '/omniharness.v1.MeshService/BroadcastEvent',
                request_serializer=omniharness__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=omniharness__pb2.BroadcastResponse.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/omniharness.v1.MeshService/ListPeers',
                request_serializer=omniharness__pb2.ListPeersRequest.SerializeToString,
                response_deserializer=omniharness__pb2.ListPeersResponse.FromString,
                _registered_method=True)


class MeshServiceServicer:
    """─── 7. MESH / P2P ───────────────────────────────────────────────────────────

    """

    def BroadcastEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastEvent,
                    request_deserializer=omniharness__pb2.BroadcastRequest.FromString,
                    response_serializer=omniharness__pb2.BroadcastResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=omniharness__pb2.ListPeersRequest.FromString,
                    response_serializer=omniharness__pb2.ListPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniharness.v1.MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omniharness.v1.MeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshService:
    """─── 7. MESH / P2P ───────────────────────────────────────────────────────────

    """

    @staticmethod
    def BroadcastEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MeshService/BroadcastEvent',
            omniharness__pb2.BroadcastRequest.SerializeToString,
            omniharness__pb2.BroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omniharness.v1.MeshService/ListPeers',
            omniharness__pb2.ListPeersRequest.SerializeToString,
            omniharness__pb2.ListPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
