[package]
name = "security-auditor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[lib]
name = "security_auditor"
path = "src/lib.rs"

[[bin]]
name = "security_auditor_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


