[package]
name = "event-processor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arc-swap = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }

[lib]
name = "event_processor"
path = "src/lib.rs"

[[bin]]
name = "event_processor_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


