[package]
name = "deployment-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[lib]
name = "deployment_manager"
path = "src/lib.rs"

[[bin]]
name = "deployment_manager_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]
tokio = { workspace = true }


