[package]
name = "bmcs-gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
regex = { workspace = true }
serde = { workspace = true }

[lib]
name = "bmcs_gateway"
path = "src/lib.rs"

[[bin]]
name = "bmcs_gateway_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


