[package]
name = "test-orchestrator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
toml = "0.8"

[lib]
name = "test_orchestrator"
path = "src/lib.rs"

[[bin]]
name = "test_orchestrator_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


