[package]
name = "bmn-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }

[lib]
name = "bmn_common"
path = "src/lib.rs"

[[bin]]
name = "bmn_common_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


