[package]
name = "config-management"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lib]
name = "config_management"
path = "src/lib.rs"

[[bin]]
name = "config_management_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


