[package]
name = "encryption-manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[lib]
name = "encryption_manager"
path = "src/lib.rs"

[[bin]]
name = "encryption_manager_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


