[package]
name = "buddy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }

[lib]
name = "buddy"
path = "src/lib.rs"

[[bin]]
name = "buddy_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


