[package]
name = "omnifile-explorer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
tracing = { workspace = true }

[lib]
name = "omnifile_explorer"
path = "src/lib.rs"

[[bin]]
name = "omnifile_explorer_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


