[package]
name = "launcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lib]
name = "launcher"
path = "src/lib.rs"

[[bin]]
name = "launcher_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


