[package]
name = "message-queue-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[lib]
name = "message_queue_core"
path = "src/lib.rs"

[[bin]]
name = "message_queue_core_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


