[package]
name = "procurement-analytics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
arc-swap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }

[lib]
name = "procurement_analytics"
path = "src/lib.rs"

[[bin]]
name = "procurement_analytics_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]


