[package]
name = "remote-access-support"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
uuid = { workspace = true }

[lib]
name = "remote_access_support"
path = "src/lib.rs"

[[bin]]
name = "remote_access_support_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


