[package]
name = "cpu-scheduler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }

[lib]
name = "cpu_scheduler"
path = "src/lib.rs"

[[bin]]
name = "cpu_scheduler_cli"
path = "src/bin/cli.rs"

[dev-dependencies]

