[package]
name = "api-gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[lib]
name = "api_gateway"
path = "src/lib.rs"

[[bin]]
name = "api_gateway_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


