[package]
name = "fabrication-control"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }

[lib]
name = "fabrication_control"
path = "src/lib.rs"

[[bin]]
name = "fabrication_control_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


