[package]
name = "model-trainer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[lib]
name = "model_trainer"
path = "src/lib.rs"

[[bin]]
name = "model_trainer_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


