[package]
name = "buir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
blake3 = "1"

[lib]
name = "buir"
path = "src/lib.rs"

[[bin]]
name = "buir_cli"
path = "src/bin/cli.rs"

[dev-dependencies]

