[package]
name = "kdb-sync"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

[lib]
name = "kdb_sync"
path = "src/lib.rs"

[[bin]]
name = "kdb_sync_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


