[package]
name = "bedf-enhancements"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }

[lib]
name = "bedf_enhancements"
path = "src/lib.rs"

[[bin]]
name = "bedf_enhancements_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


