[package]
name = "pathfinder-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
tracing = { workspace = true }

[lib]
name = "pathfinder_core"
path = "src/lib.rs"

[[bin]]
name = "pathfinder_core_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


