[package]
name = "data-sharding"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lib]
name = "data_sharding"
path = "src/lib.rs"

[[bin]]
name = "data_sharding_cli"
path = "src/bin/cli.rs"
test = false

[dev-dependencies]
tokio = { workspace = true }


