[package]
name = "universal-cache"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }

[lib]
name = "universal_cache"
path = "src/lib.rs"

[[bin]]
name = "universal_cache_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


