use std::sync::{Arc, Mutex};
use anyhow::{anyhow, Result};
use wasmtime::{Engine, Linker, Module, Store, Val};

/// Result of executing a compiled skill.
#[derive(Debug, serde::Serialize)]
pub struct SkillResult {
    /// Return code from `invoke`: 0 = success, non-zero = error.
    pub return_code: i32,
    /// Lines written via the `bonsai_log` host import during execution.
    pub log_output: Vec<String>,
}

/// Execute a compiled skill's WASM bytes.
///
/// ABI (as generated by `wasm_gen::generate_wasm_skeleton`):
///   import  env::bonsai_log(ptr: i32, len: i32)
///   export  invoke(ptr: i32, len: i32) -> i32
///
/// If the module additionally exports `memory` and `alloc(len: i32) -> i32`,
/// the JSON `args` are written into WASM memory and passed by pointer.
/// Otherwise `invoke(0, 0)` is called (skeleton mode).
pub fn execute_skill(wasm_bytes: &[u8], args: &serde_json::Value) -> Result<SkillResult> {
    let engine = Engine::default();
    let module = Module::from_binary(&engine, wasm_bytes)?;

    // Shared log capture buffer.
    let log_buf: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
    let log_buf_clone = log_buf.clone();

    let mut linker: Linker<()> = Linker::new(&engine);

    // Provide the `bonsai_log(ptr, len)` host import.
    // The skeleton calls this with whatever ptr/len was passed to invoke.
    linker.func_wrap("env", "bonsai_log", move |mut caller: wasmtime::Caller<'_, ()>, ptr: i32, len: i32| {
        if let Some(mem) = caller.get_export("memory").and_then(|e| e.into_memory()) {
            let data = mem.data(&caller);
            if let (Ok(start), Ok(end)) = (
                usize::try_from(ptr),
                usize::try_from(ptr.saturating_add(len)),
            ) {
                if end <= data.len() {
                    if let Ok(s) = std::str::from_utf8(&data[start..end]) {
                        if let Ok(mut guard) = log_buf_clone.lock() {
                            guard.push(s.to_string());
                        }
                        return;
                    }
                }
            }
        }
        // Skeleton mode: no memory accessible — log a placeholder.
        if let Ok(mut guard) = log_buf_clone.lock() {
            guard.push(format!("bonsai_log({ptr}, {len})"));
        }
    })?;

    let mut store = Store::new(&engine, ());
    let instance = linker.instantiate(&mut store, &module)?;

    // Determine how to pass args: memory + alloc export = rich mode; otherwise skeleton mode.
    let (ptr, len) = if let (Some(_mem), Some(alloc_fn)) = (
        instance.get_memory(&mut store, "memory"),
        instance.get_func(&mut store, "alloc"),
    ) {
        write_args_to_wasm(&mut store, instance, alloc_fn, args)?
    } else {
        (0i32, 0i32)
    };

    let invoke = instance
        .get_typed_func::<(i32, i32), i32>(&mut store, "invoke")
        .map_err(|e| anyhow!("invoke export not found: {e}"))?;

    let return_code = invoke.call(&mut store, (ptr, len))?;

    let log_output = log_buf.lock().unwrap().clone();
    Ok(SkillResult { return_code, log_output })
}

/// Write serialised `args` into WASM linear memory via an `alloc(len) -> ptr` export.
fn write_args_to_wasm(
    store: &mut Store<()>,
    instance: wasmtime::Instance,
    alloc_fn: wasmtime::Func,
    args: &serde_json::Value,
) -> Result<(i32, i32)> {
    let json = serde_json::to_string(args)?;
    let bytes = json.as_bytes();
    let len = bytes.len() as i32;

    // Call alloc(len) -> ptr
    let mut results = [Val::I32(0)];
    alloc_fn.call(&mut *store, &[Val::I32(len)], &mut results)?;
    let ptr = match results[0] {
        Val::I32(p) => p,
        _ => return Err(anyhow!("alloc returned non-i32")),
    };

    // Write bytes into WASM memory at ptr.
    let mem = instance
        .get_memory(&mut *store, "memory")
        .ok_or_else(|| anyhow!("memory not found after alloc"))?;
    mem.write(&mut *store, ptr as usize, bytes)?;

    Ok((ptr, len))
}
