[package]
name = "advanced-launcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }

[lib]
name = "advanced_launcher"
path = "src/lib.rs"

[[bin]]
name = "advanced_launcher_cli"
path = "src/bin/cli.rs"


