[package]
name = "kef"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
regex = { workspace = true }
ndarray = "0.15"
zstd = "0.13"
crossbeam-channel = "0.5"
rand = "0.8"
blake3 = "1.5"

[lib]
name = "kef"
path = "src/lib.rs"

[[bin]]
name = "kef_cli"
path = "src/bin/cli.rs"

[dev-dependencies]
tempfile = { workspace = true }


