[package]
name = "bmn-sources"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
bmn-common = { path = "../bmn-common" }

[lib]
name = "bmn_sources"
path = "src/lib.rs"

[[bin]]
name = "bmn_sources_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


