// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface BroadcastResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.BroadcastResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 peers = 1;</code>
   * @return The peers.
   */
  int getPeers();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();
}
