// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

/**
 * Protobuf type {@code omniharness.v1.GetSessionResp}
 */
public final class GetSessionResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:omniharness.v1.GetSessionResp)
    GetSessionRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSessionResp.newBuilder() to construct.
  private GetSessionResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSessionResp() {
    history_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSessionResp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return omniharness.v1.Omniharness.internal_static_omniharness_v1_GetSessionResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return omniharness.v1.Omniharness.internal_static_omniharness_v1_GetSessionResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            omniharness.v1.GetSessionResp.class, omniharness.v1.GetSessionResp.Builder.class);
  }

  private int bitField0_;
  public static final int SESSION_FIELD_NUMBER = 1;
  private omniharness.v1.Session session_;
  /**
   * <code>.omniharness.v1.Session session = 1;</code>
   * @return Whether the session field is set.
   */
  @java.lang.Override
  public boolean hasSession() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.omniharness.v1.Session session = 1;</code>
   * @return The session.
   */
  @java.lang.Override
  public omniharness.v1.Session getSession() {
    return session_ == null ? omniharness.v1.Session.getDefaultInstance() : session_;
  }
  /**
   * <code>.omniharness.v1.Session session = 1;</code>
   */
  @java.lang.Override
  public omniharness.v1.SessionOrBuilder getSessionOrBuilder() {
    return session_ == null ? omniharness.v1.Session.getDefaultInstance() : session_;
  }

  public static final int HISTORY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<omniharness.v1.ChatMessage> history_;
  /**
   * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
   */
  @java.lang.Override
  public java.util.List<omniharness.v1.ChatMessage> getHistoryList() {
    return history_;
  }
  /**
   * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends omniharness.v1.ChatMessageOrBuilder> 
      getHistoryOrBuilderList() {
    return history_;
  }
  /**
   * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
   */
  @java.lang.Override
  public int getHistoryCount() {
    return history_.size();
  }
  /**
   * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
   */
  @java.lang.Override
  public omniharness.v1.ChatMessage getHistory(int index) {
    return history_.get(index);
  }
  /**
   * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
   */
  @java.lang.Override
  public omniharness.v1.ChatMessageOrBuilder getHistoryOrBuilder(
      int index) {
    return history_.get(index);
  }

  public static final int FOUND_FIELD_NUMBER = 3;
  private boolean found_ = false;
  /**
   * <code>bool found = 3;</code>
   * @return The found.
   */
  @java.lang.Override
  public boolean getFound() {
    return found_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSession());
    }
    for (int i = 0; i < history_.size(); i++) {
      output.writeMessage(2, history_.get(i));
    }
    if (found_ != false) {
      output.writeBool(3, found_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSession());
    }
    for (int i = 0; i < history_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, history_.get(i));
    }
    if (found_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, found_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof omniharness.v1.GetSessionResp)) {
      return super.equals(obj);
    }
    omniharness.v1.GetSessionResp other = (omniharness.v1.GetSessionResp) obj;

    if (hasSession() != other.hasSession()) return false;
    if (hasSession()) {
      if (!getSession()
          .equals(other.getSession())) return false;
    }
    if (!getHistoryList()
        .equals(other.getHistoryList())) return false;
    if (getFound()
        != other.getFound()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSession()) {
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession().hashCode();
    }
    if (getHistoryCount() > 0) {
      hash = (37 * hash) + HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryList().hashCode();
    }
    hash = (37 * hash) + FOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFound());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static omniharness.v1.GetSessionResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.GetSessionResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.GetSessionResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static omniharness.v1.GetSessionResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static omniharness.v1.GetSessionResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static omniharness.v1.GetSessionResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(omniharness.v1.GetSessionResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code omniharness.v1.GetSessionResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:omniharness.v1.GetSessionResp)
      omniharness.v1.GetSessionRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_GetSessionResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_GetSessionResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              omniharness.v1.GetSessionResp.class, omniharness.v1.GetSessionResp.Builder.class);
    }

    // Construct using omniharness.v1.GetSessionResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSessionFieldBuilder();
        getHistoryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      session_ = null;
      if (sessionBuilder_ != null) {
        sessionBuilder_.dispose();
        sessionBuilder_ = null;
      }
      if (historyBuilder_ == null) {
        history_ = java.util.Collections.emptyList();
      } else {
        history_ = null;
        historyBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      found_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_GetSessionResp_descriptor;
    }

    @java.lang.Override
    public omniharness.v1.GetSessionResp getDefaultInstanceForType() {
      return omniharness.v1.GetSessionResp.getDefaultInstance();
    }

    @java.lang.Override
    public omniharness.v1.GetSessionResp build() {
      omniharness.v1.GetSessionResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public omniharness.v1.GetSessionResp buildPartial() {
      omniharness.v1.GetSessionResp result = new omniharness.v1.GetSessionResp(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(omniharness.v1.GetSessionResp result) {
      if (historyBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          history_ = java.util.Collections.unmodifiableList(history_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.history_ = history_;
      } else {
        result.history_ = historyBuilder_.build();
      }
    }

    private void buildPartial0(omniharness.v1.GetSessionResp result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.session_ = sessionBuilder_ == null
            ? session_
            : sessionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.found_ = found_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof omniharness.v1.GetSessionResp) {
        return mergeFrom((omniharness.v1.GetSessionResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(omniharness.v1.GetSessionResp other) {
      if (other == omniharness.v1.GetSessionResp.getDefaultInstance()) return this;
      if (other.hasSession()) {
        mergeSession(other.getSession());
      }
      if (historyBuilder_ == null) {
        if (!other.history_.isEmpty()) {
          if (history_.isEmpty()) {
            history_ = other.history_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHistoryIsMutable();
            history_.addAll(other.history_);
          }
          onChanged();
        }
      } else {
        if (!other.history_.isEmpty()) {
          if (historyBuilder_.isEmpty()) {
            historyBuilder_.dispose();
            historyBuilder_ = null;
            history_ = other.history_;
            bitField0_ = (bitField0_ & ~0x00000002);
            historyBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHistoryFieldBuilder() : null;
          } else {
            historyBuilder_.addAllMessages(other.history_);
          }
        }
      }
      if (other.getFound() != false) {
        setFound(other.getFound());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSessionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              omniharness.v1.ChatMessage m =
                  input.readMessage(
                      omniharness.v1.ChatMessage.parser(),
                      extensionRegistry);
              if (historyBuilder_ == null) {
                ensureHistoryIsMutable();
                history_.add(m);
              } else {
                historyBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              found_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private omniharness.v1.Session session_;
    private com.google.protobuf.SingleFieldBuilderV3<
        omniharness.v1.Session, omniharness.v1.Session.Builder, omniharness.v1.SessionOrBuilder> sessionBuilder_;
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     * @return Whether the session field is set.
     */
    public boolean hasSession() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     * @return The session.
     */
    public omniharness.v1.Session getSession() {
      if (sessionBuilder_ == null) {
        return session_ == null ? omniharness.v1.Session.getDefaultInstance() : session_;
      } else {
        return sessionBuilder_.getMessage();
      }
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    public Builder setSession(omniharness.v1.Session value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        session_ = value;
      } else {
        sessionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    public Builder setSession(
        omniharness.v1.Session.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        session_ = builderForValue.build();
      } else {
        sessionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    public Builder mergeSession(omniharness.v1.Session value) {
      if (sessionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          session_ != null &&
          session_ != omniharness.v1.Session.getDefaultInstance()) {
          getSessionBuilder().mergeFrom(value);
        } else {
          session_ = value;
        }
      } else {
        sessionBuilder_.mergeFrom(value);
      }
      if (session_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    public Builder clearSession() {
      bitField0_ = (bitField0_ & ~0x00000001);
      session_ = null;
      if (sessionBuilder_ != null) {
        sessionBuilder_.dispose();
        sessionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    public omniharness.v1.Session.Builder getSessionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSessionFieldBuilder().getBuilder();
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    public omniharness.v1.SessionOrBuilder getSessionOrBuilder() {
      if (sessionBuilder_ != null) {
        return sessionBuilder_.getMessageOrBuilder();
      } else {
        return session_ == null ?
            omniharness.v1.Session.getDefaultInstance() : session_;
      }
    }
    /**
     * <code>.omniharness.v1.Session session = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        omniharness.v1.Session, omniharness.v1.Session.Builder, omniharness.v1.SessionOrBuilder> 
        getSessionFieldBuilder() {
      if (sessionBuilder_ == null) {
        sessionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            omniharness.v1.Session, omniharness.v1.Session.Builder, omniharness.v1.SessionOrBuilder>(
                getSession(),
                getParentForChildren(),
                isClean());
        session_ = null;
      }
      return sessionBuilder_;
    }

    private java.util.List<omniharness.v1.ChatMessage> history_ =
      java.util.Collections.emptyList();
    private void ensureHistoryIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        history_ = new java.util.ArrayList<omniharness.v1.ChatMessage>(history_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        omniharness.v1.ChatMessage, omniharness.v1.ChatMessage.Builder, omniharness.v1.ChatMessageOrBuilder> historyBuilder_;

    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public java.util.List<omniharness.v1.ChatMessage> getHistoryList() {
      if (historyBuilder_ == null) {
        return java.util.Collections.unmodifiableList(history_);
      } else {
        return historyBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public int getHistoryCount() {
      if (historyBuilder_ == null) {
        return history_.size();
      } else {
        return historyBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public omniharness.v1.ChatMessage getHistory(int index) {
      if (historyBuilder_ == null) {
        return history_.get(index);
      } else {
        return historyBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder setHistory(
        int index, omniharness.v1.ChatMessage value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.set(index, value);
        onChanged();
      } else {
        historyBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder setHistory(
        int index, omniharness.v1.ChatMessage.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.set(index, builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder addHistory(omniharness.v1.ChatMessage value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.add(value);
        onChanged();
      } else {
        historyBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder addHistory(
        int index, omniharness.v1.ChatMessage value) {
      if (historyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoryIsMutable();
        history_.add(index, value);
        onChanged();
      } else {
        historyBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder addHistory(
        omniharness.v1.ChatMessage.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.add(builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder addHistory(
        int index, omniharness.v1.ChatMessage.Builder builderForValue) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.add(index, builderForValue.build());
        onChanged();
      } else {
        historyBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder addAllHistory(
        java.lang.Iterable<? extends omniharness.v1.ChatMessage> values) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, history_);
        onChanged();
      } else {
        historyBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder clearHistory() {
      if (historyBuilder_ == null) {
        history_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        historyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public Builder removeHistory(int index) {
      if (historyBuilder_ == null) {
        ensureHistoryIsMutable();
        history_.remove(index);
        onChanged();
      } else {
        historyBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public omniharness.v1.ChatMessage.Builder getHistoryBuilder(
        int index) {
      return getHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public omniharness.v1.ChatMessageOrBuilder getHistoryOrBuilder(
        int index) {
      if (historyBuilder_ == null) {
        return history_.get(index);  } else {
        return historyBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public java.util.List<? extends omniharness.v1.ChatMessageOrBuilder> 
         getHistoryOrBuilderList() {
      if (historyBuilder_ != null) {
        return historyBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(history_);
      }
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public omniharness.v1.ChatMessage.Builder addHistoryBuilder() {
      return getHistoryFieldBuilder().addBuilder(
          omniharness.v1.ChatMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public omniharness.v1.ChatMessage.Builder addHistoryBuilder(
        int index) {
      return getHistoryFieldBuilder().addBuilder(
          index, omniharness.v1.ChatMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .omniharness.v1.ChatMessage history = 2;</code>
     */
    public java.util.List<omniharness.v1.ChatMessage.Builder> 
         getHistoryBuilderList() {
      return getHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        omniharness.v1.ChatMessage, omniharness.v1.ChatMessage.Builder, omniharness.v1.ChatMessageOrBuilder> 
        getHistoryFieldBuilder() {
      if (historyBuilder_ == null) {
        historyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            omniharness.v1.ChatMessage, omniharness.v1.ChatMessage.Builder, omniharness.v1.ChatMessageOrBuilder>(
                history_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        history_ = null;
      }
      return historyBuilder_;
    }

    private boolean found_ ;
    /**
     * <code>bool found = 3;</code>
     * @return The found.
     */
    @java.lang.Override
    public boolean getFound() {
      return found_;
    }
    /**
     * <code>bool found = 3;</code>
     * @param value The found to set.
     * @return This builder for chaining.
     */
    public Builder setFound(boolean value) {

      found_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool found = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFound() {
      bitField0_ = (bitField0_ & ~0x00000004);
      found_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:omniharness.v1.GetSessionResp)
  }

  // @@protoc_insertion_point(class_scope:omniharness.v1.GetSessionResp)
  private static final omniharness.v1.GetSessionResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new omniharness.v1.GetSessionResp();
  }

  public static omniharness.v1.GetSessionResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSessionResp>
      PARSER = new com.google.protobuf.AbstractParser<GetSessionResp>() {
    @java.lang.Override
    public GetSessionResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSessionResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSessionResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public omniharness.v1.GetSessionResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

