// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface ListSessionsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.ListSessionsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .omniharness.v1.Session sessions = 1;</code>
   */
  java.util.List<omniharness.v1.Session> 
      getSessionsList();
  /**
   * <code>repeated .omniharness.v1.Session sessions = 1;</code>
   */
  omniharness.v1.Session getSessions(int index);
  /**
   * <code>repeated .omniharness.v1.Session sessions = 1;</code>
   */
  int getSessionsCount();
  /**
   * <code>repeated .omniharness.v1.Session sessions = 1;</code>
   */
  java.util.List<? extends omniharness.v1.SessionOrBuilder> 
      getSessionsOrBuilderList();
  /**
   * <code>repeated .omniharness.v1.Session sessions = 1;</code>
   */
  omniharness.v1.SessionOrBuilder getSessionsOrBuilder(
      int index);
}
