// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

/**
 * Protobuf type {@code omniharness.v1.ListCollResponse}
 */
public final class ListCollResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:omniharness.v1.ListCollResponse)
    ListCollResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListCollResponse.newBuilder() to construct.
  private ListCollResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListCollResponse() {
    collections_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListCollResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return omniharness.v1.Omniharness.internal_static_omniharness_v1_ListCollResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return omniharness.v1.Omniharness.internal_static_omniharness_v1_ListCollResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            omniharness.v1.ListCollResponse.class, omniharness.v1.ListCollResponse.Builder.class);
  }

  public static final int COLLECTIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList collections_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string collections = 1;</code>
   * @return A list containing the collections.
   */
  public com.google.protobuf.ProtocolStringList
      getCollectionsList() {
    return collections_;
  }
  /**
   * <code>repeated string collections = 1;</code>
   * @return The count of collections.
   */
  public int getCollectionsCount() {
    return collections_.size();
  }
  /**
   * <code>repeated string collections = 1;</code>
   * @param index The index of the element to return.
   * @return The collections at the given index.
   */
  public java.lang.String getCollections(int index) {
    return collections_.get(index);
  }
  /**
   * <code>repeated string collections = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the collections at the given index.
   */
  public com.google.protobuf.ByteString
      getCollectionsBytes(int index) {
    return collections_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < collections_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, collections_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < collections_.size(); i++) {
        dataSize += computeStringSizeNoTag(collections_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCollectionsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof omniharness.v1.ListCollResponse)) {
      return super.equals(obj);
    }
    omniharness.v1.ListCollResponse other = (omniharness.v1.ListCollResponse) obj;

    if (!getCollectionsList()
        .equals(other.getCollectionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCollectionsCount() > 0) {
      hash = (37 * hash) + COLLECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getCollectionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static omniharness.v1.ListCollResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.ListCollResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.ListCollResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static omniharness.v1.ListCollResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static omniharness.v1.ListCollResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static omniharness.v1.ListCollResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(omniharness.v1.ListCollResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code omniharness.v1.ListCollResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:omniharness.v1.ListCollResponse)
      omniharness.v1.ListCollResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_ListCollResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_ListCollResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              omniharness.v1.ListCollResponse.class, omniharness.v1.ListCollResponse.Builder.class);
    }

    // Construct using omniharness.v1.ListCollResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      collections_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_ListCollResponse_descriptor;
    }

    @java.lang.Override
    public omniharness.v1.ListCollResponse getDefaultInstanceForType() {
      return omniharness.v1.ListCollResponse.getDefaultInstance();
    }

    @java.lang.Override
    public omniharness.v1.ListCollResponse build() {
      omniharness.v1.ListCollResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public omniharness.v1.ListCollResponse buildPartial() {
      omniharness.v1.ListCollResponse result = new omniharness.v1.ListCollResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(omniharness.v1.ListCollResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        collections_.makeImmutable();
        result.collections_ = collections_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof omniharness.v1.ListCollResponse) {
        return mergeFrom((omniharness.v1.ListCollResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(omniharness.v1.ListCollResponse other) {
      if (other == omniharness.v1.ListCollResponse.getDefaultInstance()) return this;
      if (!other.collections_.isEmpty()) {
        if (collections_.isEmpty()) {
          collections_ = other.collections_;
          bitField0_ |= 0x00000001;
        } else {
          ensureCollectionsIsMutable();
          collections_.addAll(other.collections_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCollectionsIsMutable();
              collections_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList collections_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCollectionsIsMutable() {
      if (!collections_.isModifiable()) {
        collections_ = new com.google.protobuf.LazyStringArrayList(collections_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @return A list containing the collections.
     */
    public com.google.protobuf.ProtocolStringList
        getCollectionsList() {
      collections_.makeImmutable();
      return collections_;
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @return The count of collections.
     */
    public int getCollectionsCount() {
      return collections_.size();
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @param index The index of the element to return.
     * @return The collections at the given index.
     */
    public java.lang.String getCollections(int index) {
      return collections_.get(index);
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the collections at the given index.
     */
    public com.google.protobuf.ByteString
        getCollectionsBytes(int index) {
      return collections_.getByteString(index);
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @param index The index to set the value at.
     * @param value The collections to set.
     * @return This builder for chaining.
     */
    public Builder setCollections(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCollectionsIsMutable();
      collections_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @param value The collections to add.
     * @return This builder for chaining.
     */
    public Builder addCollections(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCollectionsIsMutable();
      collections_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @param values The collections to add.
     * @return This builder for chaining.
     */
    public Builder addAllCollections(
        java.lang.Iterable<java.lang.String> values) {
      ensureCollectionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, collections_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollections() {
      collections_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string collections = 1;</code>
     * @param value The bytes of the collections to add.
     * @return This builder for chaining.
     */
    public Builder addCollectionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCollectionsIsMutable();
      collections_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:omniharness.v1.ListCollResponse)
  }

  // @@protoc_insertion_point(class_scope:omniharness.v1.ListCollResponse)
  private static final omniharness.v1.ListCollResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new omniharness.v1.ListCollResponse();
  }

  public static omniharness.v1.ListCollResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListCollResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListCollResponse>() {
    @java.lang.Override
    public ListCollResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListCollResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListCollResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public omniharness.v1.ListCollResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

