// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface MemoryEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.MemoryEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string collection = 2;</code>
   * @return The collection.
   */
  java.lang.String getCollection();
  /**
   * <code>string collection = 2;</code>
   * @return The bytes for collection.
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>map&lt;string, string&gt; metadata = 4;</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 4;</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 4;</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 4;</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);

  /**
   * <code>repeated float embedding = 5;</code>
   * @return A list containing the embedding.
   */
  java.util.List<java.lang.Float> getEmbeddingList();
  /**
   * <code>repeated float embedding = 5;</code>
   * @return The count of embedding.
   */
  int getEmbeddingCount();
  /**
   * <code>repeated float embedding = 5;</code>
   * @param index The index of the element to return.
   * @return The embedding at the given index.
   */
  float getEmbedding(int index);

  /**
   * <code>int64 created_at = 6;</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <pre>
   * similarity score when returned from search
   * </pre>
   *
   * <code>double score = 7;</code>
   * @return The score.
   */
  double getScore();
}
