// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

/**
 * Protobuf type {@code omniharness.v1.MetricsResponse}
 */
public final class MetricsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:omniharness.v1.MetricsResponse)
    MetricsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetricsResponse.newBuilder() to construct.
  private MetricsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetricsResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetricsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return omniharness.v1.Omniharness.internal_static_omniharness_v1_MetricsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 7:
        return internalGetProviderCounts();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return omniharness.v1.Omniharness.internal_static_omniharness_v1_MetricsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            omniharness.v1.MetricsResponse.class, omniharness.v1.MetricsResponse.Builder.class);
  }

  public static final int AVG_LATENCY_MS_FIELD_NUMBER = 1;
  private double avgLatencyMs_ = 0D;
  /**
   * <code>double avg_latency_ms = 1;</code>
   * @return The avgLatencyMs.
   */
  @java.lang.Override
  public double getAvgLatencyMs() {
    return avgLatencyMs_;
  }

  public static final int P99_LATENCY_MS_FIELD_NUMBER = 2;
  private double p99LatencyMs_ = 0D;
  /**
   * <code>double p99_latency_ms = 2;</code>
   * @return The p99LatencyMs.
   */
  @java.lang.Override
  public double getP99LatencyMs() {
    return p99LatencyMs_;
  }

  public static final int TOTAL_TOKENS_IN_FIELD_NUMBER = 3;
  private long totalTokensIn_ = 0L;
  /**
   * <code>uint64 total_tokens_in = 3;</code>
   * @return The totalTokensIn.
   */
  @java.lang.Override
  public long getTotalTokensIn() {
    return totalTokensIn_;
  }

  public static final int TOTAL_TOKENS_OUT_FIELD_NUMBER = 4;
  private long totalTokensOut_ = 0L;
  /**
   * <code>uint64 total_tokens_out = 4;</code>
   * @return The totalTokensOut.
   */
  @java.lang.Override
  public long getTotalTokensOut() {
    return totalTokensOut_;
  }

  public static final int CACHE_HITS_FIELD_NUMBER = 5;
  private long cacheHits_ = 0L;
  /**
   * <code>uint64 cache_hits = 5;</code>
   * @return The cacheHits.
   */
  @java.lang.Override
  public long getCacheHits() {
    return cacheHits_;
  }

  public static final int CACHE_MISSES_FIELD_NUMBER = 6;
  private long cacheMisses_ = 0L;
  /**
   * <code>uint64 cache_misses = 6;</code>
   * @return The cacheMisses.
   */
  @java.lang.Override
  public long getCacheMisses() {
    return cacheMisses_;
  }

  public static final int PROVIDER_COUNTS_FIELD_NUMBER = 7;
  private static final class ProviderCountsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                omniharness.v1.Omniharness.internal_static_omniharness_v1_MetricsResponse_ProviderCountsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.UINT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> providerCounts_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetProviderCounts() {
    if (providerCounts_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ProviderCountsDefaultEntryHolder.defaultEntry);
    }
    return providerCounts_;
  }
  public int getProviderCountsCount() {
    return internalGetProviderCounts().getMap().size();
  }
  /**
   * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
   */
  @java.lang.Override
  public boolean containsProviderCounts(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetProviderCounts().getMap().containsKey(key);
  }
  /**
   * Use {@link #getProviderCountsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getProviderCounts() {
    return getProviderCountsMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getProviderCountsMap() {
    return internalGetProviderCounts().getMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
   */
  @java.lang.Override
  public long getProviderCountsOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetProviderCounts().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
   */
  @java.lang.Override
  public long getProviderCountsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetProviderCounts().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(avgLatencyMs_) != 0) {
      output.writeDouble(1, avgLatencyMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(p99LatencyMs_) != 0) {
      output.writeDouble(2, p99LatencyMs_);
    }
    if (totalTokensIn_ != 0L) {
      output.writeUInt64(3, totalTokensIn_);
    }
    if (totalTokensOut_ != 0L) {
      output.writeUInt64(4, totalTokensOut_);
    }
    if (cacheHits_ != 0L) {
      output.writeUInt64(5, cacheHits_);
    }
    if (cacheMisses_ != 0L) {
      output.writeUInt64(6, cacheMisses_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProviderCounts(),
        ProviderCountsDefaultEntryHolder.defaultEntry,
        7);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(avgLatencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, avgLatencyMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(p99LatencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, p99LatencyMs_);
    }
    if (totalTokensIn_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, totalTokensIn_);
    }
    if (totalTokensOut_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, totalTokensOut_);
    }
    if (cacheHits_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, cacheHits_);
    }
    if (cacheMisses_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, cacheMisses_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetProviderCounts().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      providerCounts__ = ProviderCountsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, providerCounts__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof omniharness.v1.MetricsResponse)) {
      return super.equals(obj);
    }
    omniharness.v1.MetricsResponse other = (omniharness.v1.MetricsResponse) obj;

    if (java.lang.Double.doubleToLongBits(getAvgLatencyMs())
        != java.lang.Double.doubleToLongBits(
            other.getAvgLatencyMs())) return false;
    if (java.lang.Double.doubleToLongBits(getP99LatencyMs())
        != java.lang.Double.doubleToLongBits(
            other.getP99LatencyMs())) return false;
    if (getTotalTokensIn()
        != other.getTotalTokensIn()) return false;
    if (getTotalTokensOut()
        != other.getTotalTokensOut()) return false;
    if (getCacheHits()
        != other.getCacheHits()) return false;
    if (getCacheMisses()
        != other.getCacheMisses()) return false;
    if (!internalGetProviderCounts().equals(
        other.internalGetProviderCounts())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVG_LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgLatencyMs()));
    hash = (37 * hash) + P99_LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getP99LatencyMs()));
    hash = (37 * hash) + TOTAL_TOKENS_IN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalTokensIn());
    hash = (37 * hash) + TOTAL_TOKENS_OUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalTokensOut());
    hash = (37 * hash) + CACHE_HITS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCacheHits());
    hash = (37 * hash) + CACHE_MISSES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCacheMisses());
    if (!internalGetProviderCounts().getMap().isEmpty()) {
      hash = (37 * hash) + PROVIDER_COUNTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProviderCounts().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static omniharness.v1.MetricsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.MetricsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static omniharness.v1.MetricsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static omniharness.v1.MetricsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static omniharness.v1.MetricsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static omniharness.v1.MetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(omniharness.v1.MetricsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code omniharness.v1.MetricsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:omniharness.v1.MetricsResponse)
      omniharness.v1.MetricsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_MetricsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetProviderCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableProviderCounts();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_MetricsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              omniharness.v1.MetricsResponse.class, omniharness.v1.MetricsResponse.Builder.class);
    }

    // Construct using omniharness.v1.MetricsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      avgLatencyMs_ = 0D;
      p99LatencyMs_ = 0D;
      totalTokensIn_ = 0L;
      totalTokensOut_ = 0L;
      cacheHits_ = 0L;
      cacheMisses_ = 0L;
      internalGetMutableProviderCounts().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return omniharness.v1.Omniharness.internal_static_omniharness_v1_MetricsResponse_descriptor;
    }

    @java.lang.Override
    public omniharness.v1.MetricsResponse getDefaultInstanceForType() {
      return omniharness.v1.MetricsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public omniharness.v1.MetricsResponse build() {
      omniharness.v1.MetricsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public omniharness.v1.MetricsResponse buildPartial() {
      omniharness.v1.MetricsResponse result = new omniharness.v1.MetricsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(omniharness.v1.MetricsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.avgLatencyMs_ = avgLatencyMs_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.p99LatencyMs_ = p99LatencyMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalTokensIn_ = totalTokensIn_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalTokensOut_ = totalTokensOut_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.cacheHits_ = cacheHits_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.cacheMisses_ = cacheMisses_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.providerCounts_ = internalGetProviderCounts();
        result.providerCounts_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof omniharness.v1.MetricsResponse) {
        return mergeFrom((omniharness.v1.MetricsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(omniharness.v1.MetricsResponse other) {
      if (other == omniharness.v1.MetricsResponse.getDefaultInstance()) return this;
      if (other.getAvgLatencyMs() != 0D) {
        setAvgLatencyMs(other.getAvgLatencyMs());
      }
      if (other.getP99LatencyMs() != 0D) {
        setP99LatencyMs(other.getP99LatencyMs());
      }
      if (other.getTotalTokensIn() != 0L) {
        setTotalTokensIn(other.getTotalTokensIn());
      }
      if (other.getTotalTokensOut() != 0L) {
        setTotalTokensOut(other.getTotalTokensOut());
      }
      if (other.getCacheHits() != 0L) {
        setCacheHits(other.getCacheHits());
      }
      if (other.getCacheMisses() != 0L) {
        setCacheMisses(other.getCacheMisses());
      }
      internalGetMutableProviderCounts().mergeFrom(
          other.internalGetProviderCounts());
      bitField0_ |= 0x00000040;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              avgLatencyMs_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              p99LatencyMs_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 24: {
              totalTokensIn_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalTokensOut_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              cacheHits_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              cacheMisses_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              providerCounts__ = input.readMessage(
                  ProviderCountsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableProviderCounts().getMutableMap().put(
                  providerCounts__.getKey(), providerCounts__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double avgLatencyMs_ ;
    /**
     * <code>double avg_latency_ms = 1;</code>
     * @return The avgLatencyMs.
     */
    @java.lang.Override
    public double getAvgLatencyMs() {
      return avgLatencyMs_;
    }
    /**
     * <code>double avg_latency_ms = 1;</code>
     * @param value The avgLatencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setAvgLatencyMs(double value) {

      avgLatencyMs_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double avg_latency_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvgLatencyMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      avgLatencyMs_ = 0D;
      onChanged();
      return this;
    }

    private double p99LatencyMs_ ;
    /**
     * <code>double p99_latency_ms = 2;</code>
     * @return The p99LatencyMs.
     */
    @java.lang.Override
    public double getP99LatencyMs() {
      return p99LatencyMs_;
    }
    /**
     * <code>double p99_latency_ms = 2;</code>
     * @param value The p99LatencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setP99LatencyMs(double value) {

      p99LatencyMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double p99_latency_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearP99LatencyMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      p99LatencyMs_ = 0D;
      onChanged();
      return this;
    }

    private long totalTokensIn_ ;
    /**
     * <code>uint64 total_tokens_in = 3;</code>
     * @return The totalTokensIn.
     */
    @java.lang.Override
    public long getTotalTokensIn() {
      return totalTokensIn_;
    }
    /**
     * <code>uint64 total_tokens_in = 3;</code>
     * @param value The totalTokensIn to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTokensIn(long value) {

      totalTokensIn_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 total_tokens_in = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTokensIn() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalTokensIn_ = 0L;
      onChanged();
      return this;
    }

    private long totalTokensOut_ ;
    /**
     * <code>uint64 total_tokens_out = 4;</code>
     * @return The totalTokensOut.
     */
    @java.lang.Override
    public long getTotalTokensOut() {
      return totalTokensOut_;
    }
    /**
     * <code>uint64 total_tokens_out = 4;</code>
     * @param value The totalTokensOut to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTokensOut(long value) {

      totalTokensOut_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 total_tokens_out = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTokensOut() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalTokensOut_ = 0L;
      onChanged();
      return this;
    }

    private long cacheHits_ ;
    /**
     * <code>uint64 cache_hits = 5;</code>
     * @return The cacheHits.
     */
    @java.lang.Override
    public long getCacheHits() {
      return cacheHits_;
    }
    /**
     * <code>uint64 cache_hits = 5;</code>
     * @param value The cacheHits to set.
     * @return This builder for chaining.
     */
    public Builder setCacheHits(long value) {

      cacheHits_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 cache_hits = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheHits() {
      bitField0_ = (bitField0_ & ~0x00000010);
      cacheHits_ = 0L;
      onChanged();
      return this;
    }

    private long cacheMisses_ ;
    /**
     * <code>uint64 cache_misses = 6;</code>
     * @return The cacheMisses.
     */
    @java.lang.Override
    public long getCacheMisses() {
      return cacheMisses_;
    }
    /**
     * <code>uint64 cache_misses = 6;</code>
     * @param value The cacheMisses to set.
     * @return This builder for chaining.
     */
    public Builder setCacheMisses(long value) {

      cacheMisses_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 cache_misses = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheMisses() {
      bitField0_ = (bitField0_ & ~0x00000020);
      cacheMisses_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> providerCounts_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetProviderCounts() {
      if (providerCounts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProviderCountsDefaultEntryHolder.defaultEntry);
      }
      return providerCounts_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableProviderCounts() {
      if (providerCounts_ == null) {
        providerCounts_ = com.google.protobuf.MapField.newMapField(
            ProviderCountsDefaultEntryHolder.defaultEntry);
      }
      if (!providerCounts_.isMutable()) {
        providerCounts_ = providerCounts_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return providerCounts_;
    }
    public int getProviderCountsCount() {
      return internalGetProviderCounts().getMap().size();
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    @java.lang.Override
    public boolean containsProviderCounts(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetProviderCounts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProviderCountsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getProviderCounts() {
      return getProviderCountsMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getProviderCountsMap() {
      return internalGetProviderCounts().getMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    @java.lang.Override
    public long getProviderCountsOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetProviderCounts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    @java.lang.Override
    public long getProviderCountsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetProviderCounts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearProviderCounts() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableProviderCounts().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    public Builder removeProviderCounts(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableProviderCounts().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableProviderCounts() {
      bitField0_ |= 0x00000040;
      return internalGetMutableProviderCounts().getMutableMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    public Builder putProviderCounts(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableProviderCounts().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; provider_counts = 7;</code>
     */
    public Builder putAllProviderCounts(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableProviderCounts().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:omniharness.v1.MetricsResponse)
  }

  // @@protoc_insertion_point(class_scope:omniharness.v1.MetricsResponse)
  private static final omniharness.v1.MetricsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new omniharness.v1.MetricsResponse();
  }

  public static omniharness.v1.MetricsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetricsResponse>
      PARSER = new com.google.protobuf.AbstractParser<MetricsResponse>() {
    @java.lang.Override
    public MetricsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetricsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetricsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public omniharness.v1.MetricsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

