// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface PeerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.Peer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string peer_id = 1;</code>
   * @return The peerId.
   */
  java.lang.String getPeerId();
  /**
   * <code>string peer_id = 1;</code>
   * @return The bytes for peerId.
   */
  com.google.protobuf.ByteString
      getPeerIdBytes();

  /**
   * <code>string addr = 2;</code>
   * @return The addr.
   */
  java.lang.String getAddr();
  /**
   * <code>string addr = 2;</code>
   * @return The bytes for addr.
   */
  com.google.protobuf.ByteString
      getAddrBytes();

  /**
   * <code>int64 connected_at = 3;</code>
   * @return The connectedAt.
   */
  long getConnectedAt();
}
