// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface RegisterModelRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.RegisterModelResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string error = 2;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
