// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>bool healthy = 2;</code>
   * @return The healthy.
   */
  boolean getHealthy();

  /**
   * <code>int64 uptime_secs = 3;</code>
   * @return The uptimeSecs.
   */
  long getUptimeSecs();

  /**
   * <code>uint64 events_stored = 4;</code>
   * @return The eventsStored.
   */
  long getEventsStored();

  /**
   * <code>uint64 requests_served = 5;</code>
   * @return The requestsServed.
   */
  long getRequestsServed();

  /**
   * <code>string tip_hash = 6;</code>
   * @return The tipHash.
   */
  java.lang.String getTipHash();
  /**
   * <code>string tip_hash = 6;</code>
   * @return The bytes for tipHash.
   */
  com.google.protobuf.ByteString
      getTipHashBytes();
}
