// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface SummarizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.SummarizeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string collection = 1;</code>
   * @return The collection.
   */
  java.lang.String getCollection();
  /**
   * <code>string collection = 1;</code>
   * @return The bytes for collection.
   */
  com.google.protobuf.ByteString
      getCollectionBytes();

  /**
   * <code>int32 max_tokens = 2;</code>
   * @return The maxTokens.
   */
  int getMaxTokens();
}
