// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface TipResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.TipResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tip_hash = 1;</code>
   * @return The tipHash.
   */
  java.lang.String getTipHash();
  /**
   * <code>string tip_hash = 1;</code>
   * @return The bytes for tipHash.
   */
  com.google.protobuf.ByteString
      getTipHashBytes();

  /**
   * <code>uint64 depth = 2;</code>
   * @return The depth.
   */
  long getDepth();
}
