// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface ToolUnregRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.ToolUnregRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
