// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface ToolDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.ToolDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * JSON Schema string
   * </pre>
   *
   * <code>string input_schema = 3;</code>
   * @return The inputSchema.
   */
  java.lang.String getInputSchema();
  /**
   * <pre>
   * JSON Schema string
   * </pre>
   *
   * <code>string input_schema = 3;</code>
   * @return The bytes for inputSchema.
   */
  com.google.protobuf.ByteString
      getInputSchemaBytes();
}
