// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: omniharness.proto

// Protobuf Java Version: 3.25.5
package omniharness.v1;

public interface ToolRegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:omniharness.v1.ToolRegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * JSON Schema
   * </pre>
   *
   * <code>string schema = 3;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <pre>
   * JSON Schema
   * </pre>
   *
   * <code>string schema = 3;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();

  /**
   * <pre>
   * HTTP endpoint for remote tools
   * </pre>
   *
   * <code>string handler_url = 4;</code>
   * @return The handlerUrl.
   */
  java.lang.String getHandlerUrl();
  /**
   * <pre>
   * HTTP endpoint for remote tools
   * </pre>
   *
   * <code>string handler_url = 4;</code>
   * @return The bytes for handlerUrl.
   */
  com.google.protobuf.ByteString
      getHandlerUrlBytes();

  /**
   * <code>bool builtin = 5;</code>
   * @return The builtin.
   */
  boolean getBuiltin();
}
