[package]
name = "kernel-snapshot"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = "1.5"
once_cell = "1"
log = "0.4"

[lib]
name = "kernel_snapshot"
path = "src/lib.rs"

[[bin]]
name = "kernel_snapshot_cli"
path = "src/bin/cli.rs"

[dev-dependencies]


