[package]
name = "bkp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
tracing = { workspace = true }
tempfile = { workspace = true }
hex = { workspace = true }
dashmap = { workspace = true }
thiserror = { workspace = true }
blake3 = "1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
zstd = "0.13"

[lib]
name = "bkp"
path = "src/lib.rs"

[[bin]]
name = "bkp_cli"
path = "src/bin/cli.rs"

[[example]]
name = "create_and_load"
path = "examples/create_and_load.rs"

[dev-dependencies]
anyhow = { workspace = true }
walkdir = "2"
